version: "3.7"

networks:
  news_network:
    driver: bridge

services:
  news-service:
    build: .
    image: news-service:1.0
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
    networks:
      - news_network

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=code4func
      - POSTGRES_DB=news
    ports:
      - '5432:5432'
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    networks:
      - news_network
